more script cleanups

diff --git a/runtime/strop b/runtime/strop
--- a/runtime/strop
+++ b/runtime/strop
@@ -7,7 +7,8 @@ trap "rm -f /tmp/strop.commands /tmp/strop.tmp[01]"   \
 
 if [ ! -r  ${SOURCE}/$1.a60 ]
 then 
-      echo Could not find $1.a60 in ${SOURCE}; exit 1
+      echo "Could not find $1.a60 in ${SOURCE}";
+      exit 1
 fi
 
 cat >/tmp/strop.commands <<++++
