fix tests add missing tests

diff --git a/runtime/tests/run_dr_tests b/runtime/tests/run_dr_tests
--- a/runtime/tests/run_dr_tests
+++ b/runtime/tests/run_dr_tests
@@ -28,7 +28,7 @@ export TESTS=${KDF9RUNTIME}/tests
 
 export EE9REGTEST=1
 
-trap "rm -f ${LOGS}/dr_test.log ${LOGS}/dr_test.diff ${KDF9RUNTIME}/settings_1.txt" 0 1 2 3
+#trap "rm -f ${LOGS}/dr_test.log ${LOGS}/dr_test.diff ${KDF9RUNTIME}/settings_1.txt" 0 1 2 3
 
 opt="-d=t -m=ahipr"
 
@@ -97,6 +97,20 @@ echo "TEST TDROUTS   11, 12, 13, 14." >>${LOGS}/dr_test.log
 >${KDF9RUNTIME}/DR0
 ucc TDROUTS
 nine_test TDROUTS ${opt}k
+fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log
+
+echo "TEST TDROUTFAILS   13."
+echo "TEST TDROUTFAILS   13." >>${LOGS}/dr_test.log
+>${KDF9RUNTIME}/DR0
+ucc TDROUTFAILS
+VARIABLE=3 nine_test TDROUTFAILS ${opt}k
+fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log
+
+echo "TEST TDROUTFAILS   11, 13."
+echo "TEST TDROUTFAILS   11, 13." >>${LOGS}/dr_test.log
+>${KDF9RUNTIME}/DR0
+ucc TDROUTFAILS
+VARIABLE=6 nine_test TDROUTFAILS ${opt}k
 fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/dr_test.log
 
 echo
diff --git a/runtime/tests/run_fd_tests b/runtime/tests/run_fd_tests
--- a/runtime/tests/run_fd_tests
+++ b/runtime/tests/run_fd_tests
@@ -28,7 +28,7 @@ export TESTS=${KDF9RUNTIME}/tests
 
 export EE9REGTEST=1
 
-trap "rm -f ${LOGS}/fd_test.log ${LOGS}/fd_test.diff ${KDF9RUNTIME}/settings_1.txt" 0 1 2 3
+#trap "rm -f ${LOGS}/fd_test.log ${LOGS}/fd_test.diff ${KDF9RUNTIME}/settings_1.txt" 0 1 2 3
 
 opt="-d=t -m=ahipr"
 
@@ -133,6 +133,42 @@ echo "TEST TFDOUTS 41, 42, 43, 44, 45." >>${LOGS}/fd_test.log
 >${KDF9RUNTIME}/FD0
 ucc TFDOUTS
 nine_test TFDOUTS $opt >>${LOGS}/fd_test.log
+fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/fd_test.log
+case $1 in
+z)
+   cat ${KDF9RUNTIME}/TP0
+   echo "======"
+   echo
+   od -c ${KDF9RUNTIME}/FD0 | more
+   echo "======"
+   echo
+   ;;
+*) ;;
+esac
+
+echo "TEST TFDOUTFAILS 41 with no discs reserved."
+echo "TEST TFDOUTFAILS 41 with no discs reserved." >>${LOGS}/fd_test.log
+>${KDF9RUNTIME}/FD0
+ucc TFDOUTFAILS
+VARIABLE=8 nine_test TFDOUTFAILS $opt >>${LOGS}/fd_test.log
+fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/fd_test.log
+case $1 in
+z)
+   cat ${KDF9RUNTIME}/TP0
+   echo "======"
+   echo
+   od -c ${KDF9RUNTIME}/FD0 | more
+   echo "======"
+   echo
+   ;;
+*) ;;
+esac
+
+echo "TEST TFDOUTFAILS 44, 45 too many 45s."
+echo "TEST TFDOUTFAILS 44, 45 too many 45s." >>${LOGS}/fd_test.log
+>${KDF9RUNTIME}/FD0
+ucc TFDOUTFAILS
+VARIABLE=4 nine_test TFDOUTFAILS $opt >>${LOGS}/fd_test.log
 fgrep "Digital signature" ${LOGS}/KDF9.log >>${LOGS}/fd_test.log
 case $1 in
 z)
