run prettifier over .sh files

diff --git a/scripts/kids b/scripts/kids
--- a/scripts/kids
+++ b/scripts/kids
@@ -20,14 +20,12 @@
 #        calls kalgol to perform compilation
 #------------------------------------------------------------------------
 
-if [ -z $KDF9RUNTIME ]
-then
+if [ -z $KDF9RUNTIME ]; then
     KDF9RUNTIME="$HOME/.kdf9"
 fi
 
-if [ $# -eq 0 ]
-then
-    set -- "-h";
+if [ $# -eq 0 ]; then
+    set -- "-h"
 fi
 
 SOURCE=${KDF9RUNTIME}/Kidsgrove
@@ -35,64 +33,63 @@ DATA=${KDF9RUNTIME}/Data
 
 while [[ "$#" -gt 0 ]]; do
     case ${1# } in
-        -h|--help) 
-            echo "KIDS - Compiles and runs a Kidsgrove Algol program.";
-            echo;
-            echo "Usage: kids [OPTION]... SOURCEFILE [DATAFILE]"
-            echo;
-            echo "  -k, --kids [LABELS|NO_OPT|DEBUG]"
-            echo "                              define the kalgol options";
-            echo "  -d, --diag [f|p|t]          define the diagnostic mode";
-            echo "  -s, --state [b|p|t]         define the run state";
-            echo "  -m, --misc [a|d|e|f|g|h|i|m|n|o|p|q|r|s|t|w|x|z|0|1|2|3|4|5|6|7|8|9]"
-            echo "                              define the miscellaneous options";
-            echo "  -nc, --no-color             do not colorize error output."
-            echo "  -TP TPMODE                  define the TP mode";
-            echo "  -TR TRMODE                  define the TR mode";
-            echo;
-            echo "Note: SOURCEFILE must exist in ${SOURCE}"
-            echo "      DATAFILE must exist in ${DATA}"
-            echo;
-            exit 0;;
-        -s=*|--state=*)
-            state=-s${1#*=};
-            ;;
-        -d=*|--diag=*)
-            mode=-d${1#*=};
-            ;;
-        -nc|--no-color)
-            nc='-nc'
-            ;;
-        -k=*|--kids=*)
-            KIDSOPTS=-k${1#*=};
-            ;;
-        -m=*|--misc=*)
-            miscellany=-m${1#*=};
-            ;;
-        -TR=*)
-            TRmode=-TR${1#*=};
-            ;;
-        -TP=*)
-            TPmode=-TP${1#*=};
-            ;;
-        *)
-            if [ -z ${source} ];
-            then
-                source="$1";
-            else
-                datafile="$1";
-            fi
-            ;;
+    -h | --help)
+        echo "KIDS - Compiles and runs a Kidsgrove Algol program."
+        echo
+        echo "Usage: kids [OPTION]... SOURCEFILE [DATAFILE]"
+        echo
+        echo "  -k, --kids [LABELS|NO_OPT|DEBUG]"
+        echo "                              define the kalgol options"
+        echo "  -d, --diag [f|p|t]          define the diagnostic mode"
+        echo "  -s, --state [b|p|t]         define the run state"
+        echo "  -m, --misc [a|d|e|f|g|h|i|m|n|o|p|q|r|s|t|w|x|z|0|1|2|3|4|5|6|7|8|9]"
+        echo "                              define the miscellaneous options"
+        echo "  -nc, --no-color             do not colorize error output."
+        echo "  -TP TPMODE                  define the TP mode"
+        echo "  -TR TRMODE                  define the TR mode"
+        echo
+        echo "Note: SOURCEFILE must exist in ${SOURCE}"
+        echo "      DATAFILE must exist in ${DATA}"
+        echo
+        exit 0
+        ;;
+    -s=* | --state=*)
+        state=-s${1#*=}
+        ;;
+    -d=* | --diag=*)
+        mode=-d${1#*=}
+        ;;
+    -nc | --no-color)
+        nc='-nc'
+        ;;
+    -k=* | --kids=*)
+        KIDSOPTS=-k${1#*=}
+        ;;
+    -m=* | --misc=*)
+        miscellany=-m${1#*=}
+        ;;
+    -TR=*)
+        TRmode=-TR${1#*=}
+        ;;
+    -TP=*)
+        TPmode=-TP${1#*=}
+        ;;
+    *)
+        if [ -z ${source} ]; then
+            source="$1"
+        else
+            datafile="$1"
+        fi
+        ;;
     esac
-    shift;
+    shift
 done
 
 kalgol ${KIDSOPTS/-k/-k=} "${nc}" ${source}
 
-if [ -s ${KDF9RUNTIME}/Binary/${source} ]
-then
-   cat ${KDF9RUNTIME}/settings_2.txt > ${KDF9RUNTIME}/settings_1.txt
-   nine "${state/-s/-s=}" "${mode/-d/-d=}" "${miscellany/-m/-m=}" "${TRmode/-TR/-TR=}" "${TPmode/-TP/-TP=}" ${source} ${datafile}
+if [ -s ${KDF9RUNTIME}/Binary/${source} ]; then
+    cat ${KDF9RUNTIME}/settings_2.txt >${KDF9RUNTIME}/settings_1.txt
+    nine "${state/-s/-s=}" "${mode/-d/-d=}" "${miscellany/-m/-m=}" "${TRmode/-TR/-TR=}" "${TPmode/-TP/-TP=}" ${source} ${datafile}
 else
-   exit 1
+    exit 1
 fi
diff --git a/scripts/ports b/scripts/ports
--- a/scripts/ports
+++ b/scripts/ports
@@ -19,14 +19,12 @@
 # ports : Convert Kidsgrove Algol to Whetstone format.
 #------------------------------------------------------------------------
 
-if [ -z $KDF9RUNTIME ]
-then
+if [ -z $KDF9RUNTIME ]; then
     KDF9RUNTIME="$HOME/.kdf9"
 fi
 
-if [ $# -eq 0 ]
-then
-    set -- "-h";
+if [ $# -eq 0 ]; then
+    set -- "-h"
 fi
 
 SOURCE=${KDF9RUNTIME}/Kidsgrove
@@ -34,24 +32,24 @@ TARGET=${KDF9RUNTIME}/Whetstone
 
 if [[ "$#" -gt 0 ]]; then
     case ${1# } in
-        -h|--help) 
-            echo "PORTS - Convert Kidsgrove Algol to Whetstone format.";
-            echo;
-            echo "Usage: ports SOURCEFILE"
-            echo;
-            echo "Note: SOURCEFILE must exist in ${SOURCE}"
-            echo;
-            exit 0;;
+    -h | --help)
+        echo "PORTS - Convert Kidsgrove Algol to Whetstone format."
+        echo
+        echo "Usage: ports SOURCEFILE"
+        echo
+        echo "Note: SOURCEFILE must exist in ${SOURCE}"
+        echo
+        exit 0
+        ;;
     esac
 fi
 
-trap "rm -f /tmp/ports.commands  /tmp/ports.tmp"   \
-      0 1 2 3
+trap "rm -f /tmp/ports.commands  /tmp/ports.tmp" \
+    0 1 2 3
 
-if [ ! -r  ${SOURCE}/$1.a60 ]
-then 
-      echo "Could not find $1.a60 in ${SOURCE}"; 
-      exit 1
+if [ ! -r ${SOURCE}/$1.a60 ]; then
+    echo "Could not find $1.a60 in ${SOURCE}"
+    exit 1
 fi
 
 cat >/tmp/ports.commands <<++++
@@ -164,4 +162,4 @@ $1|
 |
 ++++
 
-cat ${SOURCE}/$1.a60 | sed -E -f /tmp/ports.commands > ${TARGET}/$1.a60
+cat ${SOURCE}/$1.a60 | sed -E -f /tmp/ports.commands >${TARGET}/$1.a60
diff --git a/scripts/strop b/scripts/strop
--- a/scripts/strop
+++ b/scripts/strop
@@ -19,14 +19,12 @@
 # strop : Convert Whetstone Algol to Kidsgrove format.
 #------------------------------------------------------------------------
 
-if [ -z $KDF9RUNTIME ]
-then
+if [ -z $KDF9RUNTIME ]; then
     KDF9RUNTIME="$HOME/.kdf9"
 fi
 
-if [ $# -eq 0 ]
-then
-    set -- "-h";
+if [ $# -eq 0 ]; then
+    set -- "-h"
 fi
 
 SOURCE=${KDF9RUNTIME}/Whetstone
@@ -34,23 +32,23 @@ TARGET=${KDF9RUNTIME}/Kidsgrove
 
 if [[ "$#" -gt 0 ]]; then
     case ${1# } in
-        -h|--help) 
-            echo "STROP - Convert Whetstone Algol to Kidsgrove format.";
-            echo;
-            echo "Usage: strop SOURCEFILE"
-            echo;
-            echo "Note: SOURCEFILE must exist in ${SOURCE}"
-            echo;
-            exit 0;;
+    -h | --help)
+        echo "STROP - Convert Whetstone Algol to Kidsgrove format."
+        echo
+        echo "Usage: strop SOURCEFILE"
+        echo
+        echo "Note: SOURCEFILE must exist in ${SOURCE}"
+        echo
+        exit 0
+        ;;
     esac
 fi
 
 trap "rm -f /tmp/strop.commands /tmp/strop.tmp[01]" 0 1 2 3
 
-if [ ! -r  ${SOURCE}/$1.a60 ]
-then 
-      echo "Could not find $1.a60 in ${SOURCE}";
-      exit 1
+if [ ! -r ${SOURCE}/$1.a60 ]; then
+    echo "Could not find $1.a60 in ${SOURCE}"
+    exit 1
 fi
 
 cat >/tmp/strop.commands <<++++
diff --git a/scripts/strop0 b/scripts/strop0
--- a/scripts/strop0
+++ b/scripts/strop0
@@ -19,8 +19,7 @@
 # strop0 : Convert normal keyboard characters to Kidsgrove Algol format.
 #------------------------------------------------------------------------
 
-if [ -z $KDF9RUNTIME ]
-then
+if [ -z $KDF9RUNTIME ]; then
     KDF9RUNTIME="$HOME/.kdf9"
 fi
 
@@ -28,10 +27,9 @@ TARGET=${KDF9RUNTIME}/Kidsgrove
 
 trap "rm -f /tmp/strop0.commands" 0 1 2 3
 
-if [ ! -r $1.a60 ]
-then 
-      echo "Could not find $1.a60"; 
-      exit 1
+if [ ! -r $1.a60 ]; then
+    echo "Could not find $1.a60"
+    exit 1
 fi
 
 cat >/tmp/strop0.commands <<++++
@@ -45,4 +43,4 @@ s/\<=/_\</g
 s/\^\\*\\*\\*\\*\$/\|/
 ++++
 
-cat $1.a60 | sed -f /tmp/strop0.commands > ${TARGET}/$1.a60
+cat $1.a60 | sed -f /tmp/strop0.commands >${TARGET}/$1.a60
diff --git a/scripts/ucc b/scripts/ucc
--- a/scripts/ucc
+++ b/scripts/ucc
@@ -18,52 +18,49 @@
 #------------------------------------------------------------------------
 # ucc : Compiles a Usercode file to a Binary
 #------------------------------------------------------------------------
-if [ -z $KDF9RUNTIME ]
-then
+if [ -z $KDF9RUNTIME ]; then
     KDF9RUNTIME="$HOME/.kdf9"
 fi
 
-if [ $# -eq 0 ]
-then
-    set -- "-h";
+if [ $# -eq 0 ]; then
+    set -- "-h"
 fi
 
 USERCODE=${KDF9RUNTIME}/Assembly
 
 if [[ "$#" -gt 0 ]]; then
     case ${1# } in
-        -h|--help) 
-            echo "UCC - Compiles a Usercode file to a Binary.";
-            echo;
-            echo "Usage: ucc [OPTION] USERCODEFILE"
-            echo;
-            echo "   -q                quiet mode."
-            echo;
-            echo "Note: USERCODEFILE must exist in ${USERCODE}"
-            echo;
-            exit 0;;
+    -h | --help)
+        echo "UCC - Compiles a Usercode file to a Binary."
+        echo
+        echo "Usage: ucc [OPTION] USERCODEFILE"
+        echo
+        echo "   -q                quiet mode."
+        echo
+        echo "Note: USERCODEFILE must exist in ${USERCODE}"
+        echo
+        exit 0
+        ;;
     esac
 fi
 
 trap "rm -f  /tmp/a.out /tmp/mt.out" 0 1 2 3
 
-name=`basename "$1" ".k3"`
-if [ -f "${USERCODE}/$name.k3" ]
-then
-   kal3 -a ${USERCODE}/"$name.k3" > ${USERCODE}/"$name-listing.txt" 
-   if [ -s /tmp/a.out ]
-   then
-      mv -f /tmp/a.out ${KDF9RUNTIME}/Binary/"$name"
-   else
-      echo "$kal3 detected error\(s\) in $name.k3"
-      echo;
-      more ${USERCODE}/"$name-listing.txt"
-      exit 1;
-   fi
-   rm -f /tmp/a.out /tmp/mt.out
-   exit 0
+name=$(basename "$1" ".k3")
+if [ -f "${USERCODE}/$name.k3" ]; then
+    kal3 -a ${USERCODE}/"$name.k3" >${USERCODE}/"$name-listing.txt"
+    if [ -s /tmp/a.out ]; then
+        mv -f /tmp/a.out ${KDF9RUNTIME}/Binary/"$name"
+    else
+        echo "$kal3 detected error\(s\) in $name.k3"
+        echo
+        more ${USERCODE}/"$name-listing.txt"
+        exit 1
+    fi
+    rm -f /tmp/a.out /tmp/mt.out
+    exit 0
 else
-   echo "`basename "$0"`: there is no file named "$name.k3" in the ${USERCODE} folder!"
-   echo
-   exit 1
+    echo "$(basename "$0"): there is no file named "$name.k3" in the ${USERCODE} folder!"
+    echo
+    exit 1
 fi
